.\" Process this file with
.\" groff -man -Tascii harpwise.1
.\" man -l man/harpwise.1
.\"
.\" See https://www.gnu.org/software/groff/manual/html_node/index.html#Top
.TH harpwise 1

.SH "NAME"

.B harpwise
- A harmonica tool for the command line, using microphone and speaker.

.SH "SYNOPSIS"

.B harpwise
.RB {MODE}
.RB {ARGUMENTS}
.RB [OPTIONS]

.SH "DESCRIPTION"

.B harpwise
supports your harmonica practice with scales, chords and licks.
It offers various tools, an explorable quiz and may guide your jamming.
It can be used with diatonic (richter) or chromatic harmonicas in
different keys.

Invoke without arguments for introduction and usage:

.IP
harpwise
.RE

To read more details, usage examples and options for the individual modes, invoke them
without arguments, e.g.
.IP
harpwise listen
.RE

See

https://marcihm.github.io/harpwise

for full documentation.

.SH EXAMPLES

See the usage information of the individual modes.

.SH COPYRIGHT

.PP
.br
Copyright (c) 2021-2025 by Marc Ihm (marc@ihm.name) 
.br
Harpwise is subject to the MIT License, type 'harpwise --license' for details.

.SH SEE ALSO

https://marcihm.github.io/harpwise
