.\" Process this file with
.\" groff -man -Tascii harpwise.1
.\" man -l man/harpwise.1
.\"
.\" See https://www.gnu.org/software/groff/manual/html_node/index.html#Top
.TH harpwise 1

.SH "NAME"

.B harpwise
- practice harmonica with your microphone and speaker

.SH "SYNOPSIS"

.B harpwise
.RB {MODE}
.RB {ARGUMENTS}
.RB [OPTIONS]

.SH "DESCRIPTION"

.B harpwise
('wise' for short) supports the daily practice of bends,
scales, intervals or licks on a diatonic (richter) or chromatic
harmonica for various keys.

The wise recognizes single notes, that you play and it may play chords
for you (but does not recognize your chords); rhythm is out of its
scope entirely.

The primary documentation of harpwise is its usage information, that
can be retrieved by calling it without arguments:
.IP
harpwise
.RE

this man page has the very same information (so you may keep on
reading ...); but there are more usage information for the individual
modes, which are not available as man-pages (see below, on how to get
them).

.SH "MODE"

When invoking harpwise, the first argument on the commandline
specifies the mode of operation; it can be one of:
.IP - 2
.B listen:
The wise listens to your playing, e.g. to monitor bends or scales
.IP -
.B licks: 
Learn licks (only a few included, but pointers to find more)
.IP -
.B quiz: 
Train your ear and musical memory
.RE

And with a less interactive interface and not using your microphone:

.IP - 2
.B play: 
Wise plays scales, holes or licks, not asking you to play them back
.IP -
.B print:
print and annotate the holes of scales or licks given on the commandline
.IP -
.B report: 
Produce reports about licks and tags or a journal of licks played
.IP -
.B tools: 
Some simple, non-interactive tools related to basic harmonica theory		
.IP -
.B calibrate:
Wise generates samples for holes, or assists in recording your own;
this is a prereq to using many other modes; you will be asked
to invoke it, when necessary
.RE

to read more details, usage examples and options for the individual
modes, invoke them without arguments, e.g.
.IP
harpwise listen
.RE

.SH "ARGUMENTS"

After the first argument (which specifies the mode) some additional
arguments may be given:
.IP - 2
.B type:
mostly 'richter' or 'chromatic' but other choices might be defined. If
omitted, this defaults to 'richter'.
.IP -
.B KEY: 
key of harp, e.g. 'c' or 'g' or 'af' (a flat) or 'ds' (d sharp). If
omitted, this defaults to 'c'.
.IP -
.B SCALE:
scale on which you want to concentrate, e.g. 'blues', 'major_pentatonic' or 'all'. No default. As a special case and only for modes listen, quiz and licks you may give a set of holes (e.g. +1 +2 +3) as an adhoc scale.
.RE

An example using all these arguments would be:
.IP
harpwise listen richter c blues
.RE

,which (relying on defaults), could also be written as:
.IP
harpwise listen blues   
.RE

(listen to your playing, while marking notes from the blues-scale)

  harpwise listen -2 -3 +4

(listen especially for the first three notes of the blues-scale, given
 as arguments as an adhoc scale)


The possible scales depend on the chosen type of harmonica:

scales for chromatic: all, blues, one, two
  scales for richter: all, blues, blues-middle, chord-i, chord-iv, chord-v, 
    drawbends, major-pentatonic, mape, middle, minor-pentatonic, mixolydian, 
    root
  
.SH "OPTIONS"

Besides the arguments for type, key and scale, there are a lot of
options (introduced by '-'), some requiring an argument themselves.
All options are described in the usage info of the various modes.

Most arguments and options can be abbreviated, e.g 'lis'
for 'listen', 'cal' for 'calibrate' or '-t' for '--tags-any'.

Also note, that for most modes, the behaviour (e.g. the kind of
display) of the wise can be changed interactively; type 'h' to see
help on this.

.SH "SUGGESTED READING"

.IP - 2
Usage information for the individual modes
.IP -
The toplevel file README.org, also available at:

https://github.com/marcIhm/harpwise/blob/main/README.org
.RE

.SH "USER CONFIGURATION"

~/.harpwise/config.ini

.SH EXAMPLES

See the usage information of the individual modes.

.SH COPYRIGHT

.PP
.br
Copyright (c) 2021-2023 by Marc Ihm (marc@ihm.name) 
.br
This program is subject to the MIT License.

.SH SEE ALSO

Again, the usage information of the individual modes.
