#!/usr/bin/env ruby

#
# Main entry point: Load and orchestrate functions, handle global vars
#

require 'set'
require 'yaml'
require 'fileutils'
require 'open3'
require 'pp'
require_relative 'lib/helper'
require_relative 'lib/arguments'
require_relative 'lib/config'
require_relative 'lib/interaction'
require_relative 'lib/sound_files'
require_relative 'lib/analyse'
require_relative 'lib/get_hole'
require_relative 'lib/listen'
require_relative 'lib/calibrate'
require_relative 'lib/quiz'


check_installation

$term_height, $term_width = prepare_screen

set_global_vars_early

$conf = read_technical_config
$mode, $type, $key, $scale, $opts = parse_arguments

$harp, $harp_holes, $scale_holes, $scale_notes, $intervals = read_musical_config
$chart, $hole2chart = read_chart

# adjust some data
$line_comment_big += 2 if $mode == :quiz

set_global_vars_late

$freq2hole = read_calibration unless $mode == :calibrate

if $opts[:debug]
  %w($chart $harp $conf $opts $scale_notes $scale_holes $type $scale $key).each do |var|
    puts "\n#{var}:", eval("#{var}.pretty_inspect")
  end
  print 'press RETURN to continue: '
  STDIN.gets
end

Signal.trap('SIGINT') do
  print "\e[#{$line_listen}H" if $move_down_on_exit
  puts "\nexit on ctrl-c"
  exit 1
end


at_exit do
  dismiss_term
end


case $mode
when :quiz
  do_quiz
when :listen
  do_listen
when :calibrate
  if $opts[:auto]
    do_calibrate_auto
  else
    do_calibrate_assistant
  end
end
