#!/usr/bin/env ruby

#
# Main entry point: Load and orchestrate functions, handle global vars
#

require 'set'
require 'yaml'
require 'fileutils'
require 'open3'
require 'pp'
require 'sys/proctable'
require 'tmpdir'
require_relative 'lib/helper'
require_relative 'lib/arguments'
require_relative 'lib/config'
require_relative 'lib/interaction'
require_relative 'lib/sound_driver'
require_relative 'lib/analyze'
require_relative 'lib/get_hole'
require_relative 'lib/listen'
require_relative 'lib/calibrate'
require_relative 'lib/quiz'

$program_start = Time.now.to_f

myself = File.basename($0)
Sys::ProcTable.ps{ |p|
  err_b "An instance of this program is already running: pid: #{p.pid}, commandline: '#{p.cmdline}'" if Process.pid != p.pid && p.cmdline[myself] && p.cmdline['ruby']
}

check_installation

$term_height, $term_width = prepare_screen

set_global_vars_early

$conf = read_technical_config

$mode, $type, $key, $scale, $opts = parse_arguments

# we need to have mode for this
calculate_screen_layout
  
$harp, $harp_holes, $scale_holes, $scale_notes, $hole2rem, $hole2flags, $semi2hole, $intervals = read_musical_config
$chart, $hole2chart = read_chart
err_b "Option '--ref' needs a valid hole as an argument, not '#{$opts[:ref]}'" if $opts[:ref] && !$harp_holes.include?($opts[:ref])
$hole_ref = $opts[:ref]

set_global_vars_late
check_screen

$freq2hole = read_calibration unless $mode == :calibrate

Thread.report_on_exception = false


Signal.trap('SIGINT') do
  print "\e[#{$line_call2}H" if $move_down_on_exit
  fail "\nexit on ctrl-c" if $opts[:debug]
  puts "\nexit on ctrl-c"
  exit 1
end


if $mode == :listen || $mode == :quiz
  Signal.trap('WINCH') do
    $ctl_sig_winch = true
  end
end


at_exit do
  sane_term
  Thread.list.each do |thread|
    thread.exit unless thread == Thread.current
  end
end


# some regression tests
note2semi('a4') == 0 or fail 'Internal error'
semi2note(0) == 'a4' or fail 'Internal error'

case $mode
when :quiz
  do_quiz
when :listen
  do_listen
when :calibrate
  if $opts[:auto]
    do_calibrate_auto
  else
    do_calibrate_assistant
  end
end
