
* CANCELED Regarding wslq in [2021-12-31 Fri]

  - Check if arecord still delivers samples from previous invocations; if not,
    remove workarounds.
  - Check if aplay still has problem with stuttering; check if paplay
    does better returns only after playing the whole sample.

* Ideen für neue Feature

** TODO [2022-05-09 Mon] Anzeige der Länge eines mp3 in "play_recording"

   allerdings bekommt man die Länge nur aus sox und das braucht eine
   Weile dafür; also muss man das Ergebnis cachen (vermutlich in
   sox_query).

** TODO [2022-05-11 Wed] Längen in der Zusammenfassung der licks 

   (per '--tags print') auch eine Gruppierung/Histogramm nach Länge
   anzeigen.

** DONE [2022-05-11 Wed] Prüfen und präzisieren

   Ist mir rec.length nicht eher rec.end gemeint ?

** TODO [2022-05-16 Mon] Klasse statt Lambdas

   In get_hole, z.B. GHController (get-hole-controller) ?

** DONE [2022-05-16 Mon] Nur Teile der Aufnahme spielen

   Z.B. --partial 1/5 oder any/3 
** TODO [2022-05-19 Thu] Hole grau anzeigen

   Wenn es zwar aktuell nicht mehr richtig ist aber davor richtig war
