
* CANCELED Regarding wslq in [2021-12-31 Fri]

  - Check if arecord still delivers samples from previous invocations; if not,
    remove workarounds.
  - Check if aplay still has problem with stuttering; check if paplay
    does better returns only after playing the whole sample.

* Ideen für neue Feature

** TODO [2022-05-09 Mon] Anzeige der Länge eines mp3 in "play_recording"

   allerdings bekommt man die Länge nur aus sox und das braucht eine
   Weile dafür; also muss man das Ergebnis cachen (vermutlich in
   sox_query).

** DONE [2022-05-11 Wed] Anzahl Löcher in der Zusammenfassung der licks 

   (per '--tags print') auch eine Gruppierung/Histogramm nach Länge
   (i.e. Anzahl Löcher) anzeigen.

** DONE [2022-05-11 Wed] Prüfen und präzisieren

   Ist mit rec.length nicht eher rec.end gemeint ?

** CANCELED [2022-05-16 Mon] Klasse statt Lambdas

   In get_hole, z.B. GHController (get-hole-controller) ?

** DONE [2022-05-16 Mon] Nur Teile der Aufnahme spielen

   Z.B. --partial 1/5 oder any/3 

** DONE [2022-05-19 Thu] Hole grau anzeigen

   Wenn es zwar aktuell nicht mehr richtig ist aber davor richtig war

   Gelb

** DONE [2022-05-25 Wed] Gleichverteilung beim Würfeln des nächsten Licks

   Und so daß keins zweimal hintereinander kommt.

** DONE [2022-05-25 Wed] Default in den Licks überschreibt den nächsten

   Und ersetzt ihn nicht
