FROM ubuntu:rolling
MAINTAINER Marc Ihm (marc@ihm.name)
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -y
RUN apt-get install -y sudo
RUN apt-get install -y ca-certificates
COPY harp-wizard /harp-wizard
WORKDIR /harp-wizard
RUN bash ./install/install-dependencies-on-ubuntu.sh
ENTRYPOINT ["./harp-wizard"]
