FROM ubuntu:rolling
MAINTAINER Marc Ihm (marc@ihm.name)
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -y
RUN apt-get install -y sudo
RUN apt-get install -y ca-certificates
COPY harpwise /harpwise
WORKDIR /harpwise
RUN bash ./install/install-dependencies-on-ubuntu.sh
ENTRYPOINT ["./harpwise"]
