name: harpwise
base: core24
version: '6.10.2'
summary: A harmonica tool for the commandline using microphone and speaker.
description: |
  Harpwise assists your daily practice with scales and licks. It offers various
  tools, an explorable quiz and supports your jamming. It can be used with
  diatonic (richter) or chromatic harmonicas in different keys.
grade: devel
confinement: devmode

apps:
  harpwise:
    environment:
      # core24 includes ruby 3.2
      # RUBYLIB is prepended to LOAD_PATH
      RUBYLIB: $SNAP/usr/lib/ruby/3.2.0:$SNAP/usr/lib/x86_64-linux-gnu/ruby/3.2.0
      GEM_PATH: $SNAP/usr/lib/ruby/3.2.0
    command: usr/bin/ruby $SNAP/harpwise

parts:
  harpwise:
    plugin: dump
    source: https://github.com/marcIhm/harpwise/archive/refs/tags/$SNAPCRAFT_PROJECT_VERSION.tar.gz
    stage-packages:
      - ruby
      - libruby
      - rubygems
      - coreutils
      - sox
      - libsox-fmt-mp3 
      - aubio-tools
      - figlet
      - toilet
      
    