name: harpwise
# we need core24 rather than core22, because our minimum ruby-version is 3.1
# and core22 only includes 3.0
base: core24
version: '6.10.3'
summary: A harmonica tool for the commandline using microphone and speaker.
description: |
  Harpwise assists your daily practice with scales and licks. It offers various
  tools, an explorable quiz and supports your jamming. It can be used with
  diatonic (richter) or chromatic harmonicas in different keys.
grade: devel
confinement: devmode

apps:
  harpwise:
    environment:
      # core24 includes ruby 3.2
      # RUBYLIB is prepended to LOAD_PATH
      RUBYLIB: $SNAP/usr/lib/ruby/3.2.0:$SNAP/usr/lib/x86_64-linux-gnu/ruby/3.2.0
      GEM_PATH: $SNAP/usr/lib/ruby/3.2.0
    command: usr/bin/ruby $SNAP/harpwise

parts:
  harpwise:
    plugin: dump
    source: https://github.com/marcIhm/harpwise/archive/refs/tags/$SNAPCRAFT_PROJECT_VERSION.tar.gz
    stage-packages:
      - ruby
      - libruby
      - rubygems
      - coreutils
      - libsox-fmt-mp3
      - sox
      - aubio-tools
      - figlet
      - toilet

layout:             
  $SNAP/usr/bin/figlet:
    symlink: $SNAP/usr/bin/figlet-figlet
  # make mp3 available for aubiopitch, because setting LD_LIBRARY_PATH does not work
  /usr/lib/x86_64-linux-gnu/sox:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/sox

lint:
  ignore:
    # otherwise we see a lot of warnings related to unused libraries
    - library
    
