# -*- fill-column: 78 -*-

* Overview

  The configuration is distributed among various files and directories.

  Technical Config:
  
  - config.yaml :: Main config file; see comments within for some
    explanations.
		   
  - ~/.harp_scale_trainer/config_merge.yaml :: Optional, may contain any of the config-keys from
    config.yaml and then overrides those; not included in git-versioning.

  - intervals.yaml :: Names for selected intervals.


  Each type of harmonica (e.g. richter) has a directory with its own 
  Musical Config:

  - intervals.yaml :: If this file is present within a subdirectory, it
    overrides the one directly within config.

  - holes.yaml :: Maps holes to notes for a harmonica of key c. All other keys
    will be automatically derived from this one

  - scales_SCALE_with_holes.yaml :: List of holes for scale SCALE

  - scales_SCALE_with_notes.yaml :: List of notes for scale SCALE

  
  Each scale (e.g. blues or mape) has its own file and can be either notated
  with holes or notes, but NOT both. However, if a scale with notes is parsed,
  the same scale is written out (prefixed with the word 'derived') with holes
  and vice versa. So for example using scale_blues_with_holes.yaml will
  trigger the creation of derived_scale_blues_with_notes.yaml.

  To adjust configuration you may add config_merge.yaml to override selected
  settings (e.g. the default harmonica-type).

* Creating a new type of harmonica

  (Please also read the section "A word on holes" from the toplevel README.org too)

  You may create a new type of harmonica (e.g. country-tuning) by copying one of
  the existing dirs (e.g. richter) to a new name (country) and modify the
  contained files accordingly.

  In this process you may remove some of the copied scale-files and rename
  some of the derived scale-files to remove the prefix 'derved_'; this way you
  can choose which scales you want to have for your new type of harmonica, and
  how you want to notate these scales (with holes or with notes).

  Let error messages be your guide in this process.

  Also note, that the hole-names (e.g. "-1") used throughout the configuration
  files are more or less customary and can be chosen at will; they only need
  to be consistent within one type of harmonica (e.g richter). A different
  type (e.g. chromatic) may use totally or partially different names for holes
  (e.g. "-1b").

  The note-names (e.g. "a4" or gs5) on the other hand follow a strict schema,
  from which you may not deviate.
