Utility scripts, not needed for normal operation of harpwise, but
useful for some advanced or special use-cases.

* timed.rb

  A remote control for harpwise with a time table for switching licks
  and scales while playing a backing track.

  To use timed.rb, you need *two* terminals. In the first one start
  (e.g.):

    harpwise listen --sc-prog 12bar --lick-prog box1 --no-player-info --read-fifo

  and after that, in the second terminal start:

    ./timed.rb timed_sample.json

  which however requires you to edit time_sample.json first and put in
  the name of decent sound-file of your own as well as timestamps for
  the chord-changes within this file.

  Once started, harpwise (as usual) shows your playing on the chart
  and how it matches the current chord with respect to the backing
  track beeing played. The scale progression (12bar) in this and many
  cases is really a chord-progression (I, IV, V) and is switched along
  by timed.rb (using the fifo).  The script timed.rb uses the
  timestamps from the json-file to trigger harpwise at the right
  moment.

  With this scripted chord-progression you always know the notes from
  the chord and can see immediately, if you play within or without. In
  addition you see the licks of the lick-progression (box1) which are
  switched along with the song too. These can give your playing a
  solid starting point until you start improvising.

  Admittedly, preparing the json-file with timestamps needs some
  technical preparation-work; however, your ear and e.g. audacity (by
  using and exporting text-markers) makes this quite doable.

  And as you may find, this labor can help with a gentle transition
  from just playing tabs into the realm of free improvisation.

  Note, that in this setting you may either need headphones or a
  hand-held microphone to keep apart your playing from the backing
  track beeing played and thus save harpwise from getting confused.
  
* harpwise_historic_with_fzf.sh
  
  Bash-function for an interactive search in the history of invocations
  of harpwise.

  This uses fzf (fuzzy-finder, which must be installed first) and may
  provide a more specific search experience than the normal history
  search of your shell.

  This file contains some useful comments on its own usage.
