Scripts to install dependencies for harpwise for different
linux-distributions or WSL2 under Windows

* Downloading harpwise

  You may either clone the repo OR just download the zip-file from
  github.

  In either case, you will end up with a directory ~/harpwise

** Clone the repo

   Within your home directory type:

   - git clone https://github.com/marcIhm/harpwise.git

   This will give you the full repository with its history and will make
   it easier to contribute (e.g. new scales or harmonica types).

   The advantage (over downloading just the zip as described below, is
   that you will easily be able tu update to newer versions by typing
   "git pull" within ~/harpwise)

** Alternative: Download the zip-file 

   Within your home directory type:

   - wget https://github.com/marcIhm/harpwise/archive/main.zip
   - unzip harpwise-main.zip
   - rm harpwise-main.zip
   - mv harpwise-main harpwise
  
* Installing dependencies

  Remark: All dependencies are runtime-only, as there is no
  build-process for harpwise (beeing a ruby-script, not depending on
  any binary gems).

  For Ubuntu and thus WSL2 under Windows:

    - cd install
    - ./install-dependencies-on-ubuntu.sh 2>&1 | tee ~/harpwise/install.log

  may be suitable for other debian-based systems too (which use apt to
  install software).


  For fedora, redhat, centos:

    - cd install
    - ./install-dependencies-on-fedora.sh 2>&1 | tee ~/harpwise/install.log

  might also work on systems derived from fedora (which use yum to
  install software).


  Both scripts are fairly simple and you are invited to inspect them
  before running.


  As suggested, you may capture the output of the script; this is
  helpful, if you have problems during installation, as you may send
  me (marc@ihm.name) the install.log

* Configuration of your sound system (not covered)

  Please note, that after this installation you should be able to record
  and play sound via sox, e.g.:

  - rec -r 44100 -e signed-integer foo.wav trim 0 1
  - play foo.wav

  if this gives you errors or no audible result, you need to fix this
  first (which is beyond the scope of this readme).

* Uninstalling (only half covered)

** Uninstalling harpwise itself

   Just remove the directory ~/harpwise which you downloaded
   initially.

   The data of harpwise (samples for calibration and
   journal.txt) is kept in the hidden directory ~/.harpwise,
   which you may or may not want to remove too.

** Uninstalling dependencies 

   There is no uninstaller for the dependencies.

   To uninstall manually, you need to review the logfile from the
   installation and remove those packages, that have not been present
   on your system initially.

   However, in general, the number of packages installed as
   dependencies and their disk-usage is fairly low, so there is not
   much pressure to remove those dependencies.

* Testing the installer

  As a maintainer, see tests/installer for a way to test these scripts
  in a container.
