** Table of Contents  :TOC_1:
- [[#installing-wsl2-on-windows][Installing wsl2 on Windows]]
- [[#a-shorter-way-for-linux-ubuntu][A shorter way for Linux (ubuntu)]]
- [[#downloading-harpwise][Downloading harpwise]]
- [[#installing-dependencies-on-linux][Installing dependencies on Linux]]
- [[#installing-dependencies-on-macos][Installing dependencies on MacOS]]
- [[#testing-your-sound-system][Testing your sound system]]
- [[#uninstalling][Uninstalling]]
- [[#testing-the-installer-scripts][Testing the installer-scripts]]

* Installing wsl2 on Windows

  wsl2 this gives you a great installation of Linux within windows.

  wsl2 is a very useful and interesting system by itself alone, but it
  will take some time to get used to. Do not fear the commandline !

  The internet has many guides that explain this process ("install
  wsl2") in detail; please refer to them.

  After that you essentially have a linux-system (ubuntu) under
  windows, so that you may open the wsl2 commandline and proceed with
  the general and linux-specific instructions (downloading,
  dependencies, or the sorter way)

* A shorter way for Linux (ubuntu)

  As harpwise is part of the ubuntu repositories, you may only need do
  this:

  - sudo apt install harpwise

  and simply start it by typing: harpwise

  Downloading harpwise and installing its dependencies, can then be
  skipped.
  
* Downloading harpwise

  This is the same process for linux, windows and macos
  
  You may either clone the repo OR just download the zip-file from
  github.

  In either case, you will end up with a directory ~/harpwise

** Clone the repo

   Within your home directory type:

   - git clone https://github.com/marcIhm/harpwise.git

   This will give you the full repository with its history and will make
   it easier to contribute (e.g. new scales or harmonica types).

   The advantage (over downloading just the zip as described below, is
   that you will easily be able tu update to newer versions by typing
   "git pull" within ~/harpwise)

** Alternative: Download the zip-file 

   Within your home directory type:

   - wget https://github.com/marcIhm/harpwise/archive/main.zip
   - unzip harpwise-main.zip
   - rm harpwise-main.zip
   - mv harpwise-main harpwise
     
* Installing dependencies on Linux

  For Ubuntu and thus WSL2 under Windows:

  - cd ~/harpwise/install
  - . ./install-dependencies-on-ubuntu.sh  
  
  
  For fedora, redhat, centos, etc.:

  - cd ~/harpwise/install
  - . ./install-dependencies-on-fedora.sh


  Both scripts are fairly simple and you are invited to inspect them
  before running.

* Installing dependencies on MacOS

  This requires homebrew, which is an excellent system with many
  programs e.g. for the commandline.

  The internet is full of guides on how to install Homebrew; please
  refer to them.

  After that you may proceed:

  - cd ~/harpwise/install
  - . ./install-dependencies-on-macos.sh
  
* Testing your sound system

  Please note, that after this installation you should be able to record
  and then play sound via sox, e.g.:

  - rec foo.wav trim 0 1  ## maybe count "1,2,3" to get something recorded
  - play foo.wav

  if this gives you errors or no audible result, you need to fix this
  first, which however is beyond the scope of this readme.

* Uninstalling

** Uninstalling harpwise itself

   Just remove the directory ~/harpwise which you downloaded
   initially.

   The data of harpwise (samples, licks, journal and much more) is
   kept in the hidden directory ~/.harpwise, which you may or may not
   want to remove too.

** Uninstalling dependencies 

   There is no uninstaller for the dependencies.

   To uninstall manually, you need to remove the packages by hand, e.g.

   - sudo apt remove figlet   ## ubuntu and wsl2 (windows)
   - sudo yum remove figlet   ## fedora
   - brew remove figlet       ## MacOS

   and the same for the handful of other packages that were installed
   as dependencis of harpwise (see the install script).

   However, in general, the number of packages installed as
   dependencies and their disk-usage is fairly low, so there is not
   much pressure to remove them.

* Testing the installer-scripts

  As a maintainer, see tests/installer for a way to test these scripts
  in a container.
