** Table of Contents  :TOC_1:
- [[#installing-wsl2-on-windows][Installing wsl2 on Windows]]
- [[#a-shorter-way-for-linux-ubuntu][A shorter way for Linux (Ubuntu)]]
- [[#downloading-harpwise][Downloading harpwise]]
- [[#installing-dependencies-on-linux][Installing dependencies on Linux]]
- [[#installing-dependencies-on-macos][Installing dependencies on MacOS]]
- [[#testing-your-sound-system][Testing your sound system]]
- [[#uninstalling][Uninstalling]]
- [[#testing-the-installer-scripts][Testing the installer-scripts]]
- [[#building-a-snap-work-in-progress][Building a snap (work in progress)]]

Please see the main README first, which has a short and easy chapter on
installing harpwise on some major platforms.

Come back here only for special cases.

* Installing wsl2 on Windows

  wsl2 gives you a great installation of Linux within windows.

  It is a very useful and interesting system by itself and it might
  take some time to master it. The small set of commands however, that
  is required to install and use harpwise, is spelled out
  below in detail.

  The internet has many guides that explain the process of installing
  wsl2 in detail; please refer to them for instructions, e.g.:
  https://learn.microsoft.com/en-us/windows/wsl/install

  After that you have a full Linux system (Ubuntu) under Windows, so
  that you can open the wsl2 commandline and proceed with the general
  and Linux-specific instructions below (downloading, dependencies, or
  the 'shorter way' via apt).

* A shorter way for Linux (Ubuntu)

  As harpwise is part of the Ubuntu repositories, it suffices to type:

  sudo apt install harpwise

  and simply start harpwise by typing:

  harpwise

  Downloading harpwise and installing its dependencies (see below),
  can then be skipped. However, the version from the repositories is
  not always the most recent, so that you may miss out the latest
  features and bugfixes this way.
  
* Downloading harpwise

  This is the same process for Linux, Windows and MacOS
  
  You may either clone the repo OR just download the zip-file from
  Github (see below).

  In either case, you will end up with a directory ~/harpwise

** Clone the repo

   Within your home directory type:

   git clone https://github.com/marcIhm/harpwise.git

   This will give you the full repository with its history and will make
   it easier to contribute (e.g. new scales or harmonica types).

   The advantage (over downloading just the zip as described below) is
   that you will easily be able to update to newer versions by typing
   'git pull' within ~/harpwise.

** Alternative: Download the zip-file 

   Within your home directory type:

   - wget https://github.com/marcIhm/harpwise/archive/main.zip
   - unzip harpwise-main.zip
   - rm harpwise-main.zip
   - mv harpwise-main harpwise
     
* Installing dependencies on Linux

  For Ubuntu and thus WSL2 under Windows:

  - cd ~/harpwise/install
  - . ./install-dependencies-on-ubuntu.sh  
  
  
  For Fedora, RedHat, Centos, etc.:

  - cd ~/harpwise/install
  - . ./install-dependencies-on-fedora.sh


  Both scripts are fairly simple and you are invited to inspect them.

* Installing dependencies on MacOS

  This requires homebrew, which is an excellent system by itself with
  many useful programs for the commandline (and more).

  The internet is full of guides on how to install Homebrew; please
  refer to them for instructions,
  e.g. https://docs.brew.sh/Installation

  After that you may proceed:

  - cd ~/harpwise/install
  - . ./install-dependencies-on-macos.sh
  
* Testing your sound system

  Please note, that after installing the dependencies (see above) you
  should be able to record and then play sound via sox, e.g.:

  - rec foo.wav trim 0 1   ## maybe count '1,2,3' to get something recorded
  - play foo.wav

  if this gives you errors or no audible result, you need to fix this
  first, which however is beyond the scope of this readme.

* Uninstalling

** Uninstalling harpwise itself

   Just remove the directory ~/harpwise which you downloaded
   initially.

   The data of harpwise (samples, licks, journal and much more) is
   kept in directory ~/harpwise, which you may or may not want
   to remove too.

** Uninstalling dependencies 

   There is no uninstaller for the dependencies.

   To uninstall manually, you need to remove the packages by hand,
   e.g. for the package 'figlet':

   - sudo apt remove figlet   ## Ubuntu and wsl2 (Windows)
   - sudo yum remove figlet   ## Fedora
   - brew remove figlet       ## MacOS

   and the same for the handful of other packages that were installed
   as dependencies of harpwise (see the install script).

   However, in general, the number of packages installed as
   dependencies and their disk-usage is fairly low, so there is not
   much pressure to remove them.

* Testing the installer-scripts

  As a maintainer, see tests/installer for a way to test the install
  scripts in a container.

* Building a snap

  Harpwise is available as a snap; see directory snap for details.
