* Prepare to build in ~/hw-snap

  We do this, because the source-property of a snap-part can only
  access files/directories from the same dir, where snapcraft.yaml
  resides; so directories harpwise and file snapcraft.yaml need to be
  neighbours (live in same dir).

  On the other hand, we want snapcraft.yaml to be part of repo
  harpwise. Therefore we use rebuild.sh, which updates things within
  ~/hw-snap. rebuild.sh is a softlink, which needs to be created by
  hand.

  As ~/hw-snap is not part of the git repo, make sure not to edit there !
    
* Development cycle (in ~/hw-snap)

  ./harpwise/snap/rebuild.sh
  
  - snap warnings
  - sudo snap okay
  
  - snap run --shell harpwise
    - cd $SNAP
  - harpwise listen c

  - snap connections harpwise
  - snap connect harpwise:home
    
  – snapcraft login
  
  – snapcraft upload --release=latest/edge harpwise_*_amd64.snap
  – snapcraft upload --release=latest/stable harpwise_*_amd64.snap                                                                         

* Useful links related for building snaps  
** ruby

   - https://github.com/ronin-rb/snap/blob/2b98d2ad9fd7077037d65d21639d057717684b5e/snap/snapcraft.yaml
   - https://github.com/kbsecret/kbsecret/issues/3

** sound

   - https://forum.snapcraft.io/t/is-it-possible-to-create-a-symlink-from-snap-etc-to-snap-data/31114/6
   - https://forum.snapcraft.io/t/snap-example-with-audio-playback-and-play-sox-command/24067/9
     - https://wiki.freepascal.org/Create_snap_package#Sound_support
   - https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1879229
   - https://github.com/ogra1/pulse-server/blob/main/snap/snapcraft.yaml

** Home

   - https://snapcraft.io/docs/personal-files-interface
   - https://forum.snapcraft.io/t/use-of-home-and-network-plugs/2587/20

* Comparison with audacity

  Compare with:

  https://github.com/diddlesnaps/audacity/blob/master/snap/snapcraft.yaml
  
  At startup the audacity snap suggests:

  sudo snap connect audacity:alsa
  
  But this does not seem to help. In any case (for me) recording with
  audacity starts with a crack and does not capture the first (or so)
  second. But of course, that might be related with my ubuntu-25
  install. In any case the problem is similar to the ones I have with
  "harpwise tools diag".
  
  So:

  sudo snap connect harpwise:alsa

  does not seem to help; check with:

  snap connections harpwise
  
* Possible icons for snapstore

  https://www.istockphoto.com/en/vector/harmonica-musical-instrument-icon-gm1302759223-394403290

  https://www.istockphoto.com/en/vector/the-girl-is-playing-the-harmonica-gm1490459105-515030329

  https://www.istockphoto.com/en/vector/kids-musical-instrument-harmonica-drawn-in-cartoon-style-vector-illustration-gm1365215514-436154913
  
  https://www.istockphoto.com/en/vector/black-filled-harmonica-musical-instrument-icon-isolated-gm1317650389-405020318

  https://thenounproject.com/icon/harmonica-1601956/
