name: harpwise

#
# This is the snap for harpwise
# See: https://github.com/marcIhm/harpwise
#  

# We require core24 rather than core22, because our minimum ruby-version
# is 3.1 and core22 only includes 3.0
base: core24
version: '6.10.8'
summary: A harmonica tool for the command line, using microphone and speaker.
description: |
  Harpwise supports your daily practice with scales and licks. It offers various
  tools, an explorable quiz and may guide your jamming. It can be used with
  diatonic (richter) or chromatic harmonicas in different keys.
# Unfortunately we still have audio issues, but they may also be
# related with ubuntu 25 beeing just released
grade: devel
confinement: devmode

apps:
  harpwise:
    environment:
      # core24 includes ruby 3.2
      # RUBYLIB is prepended to LOAD_PATH
      RUBYLIB: $SNAP/usr/lib/ruby/3.2.0:$SNAP/usr/lib/x86_64-linux-gnu/ruby/3.2.0
      GEM_PATH: $SNAP/usr/lib/ruby/3.2.0
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio      
      PULSE_SERVER: unix:/run/user/1000/pulse/native
      TERMINFO_DIRS: $SNAP/lib/terminfo:$SNAP/usr/share/terminfo
    command: usr/bin/ruby $SNAP/harpwise
    plugs:
      - alsa
      - audio-playback
      - audio-record
      - pulseaudio
      # we read and write ~/.harpwise; and for testing ~/dot_harpwise
      # as well as several dirs and files ~/.harpwise*
      - home

parts:
  harpwise:
    plugin: dump
    # during development use local dir directly; afterward, 
    # to get a defined version, pull from github
    source: harpwise
#    source: https://github.com/marcIhm/harpwise/archive/refs/tags/$SNAPCRAFT_PROJECT_VERSION.tar.gz
    stage-packages:
      - ruby
      - libruby
      - rubygems
      - coreutils
      - sox
      - libsox-fmt-mp3
      - libsox-fmt-pulse
      - libpulse0
      - alsa-utils
      - pipewire-alsa
      - aubio-tools
      - figlet
      - toilet
      - ncurses-base
      - ncurses-term
      - pv

layout:             
  $SNAP/usr/bin/figlet:
    symlink: $SNAP/usr/bin/figlet-figlet
  /usr/lib/x86_64-linux-gnu/sox:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/sox
  /usr/share/figlet:
    bind: $SNAP/usr/share/figlet
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

lint:
  ignore:
    - library
    
