name: harpwise

#
# This is the snap for harpwise
# See: https://github.com/marcIhm/harpwise
#  

# We require core24 rather than core22, because our minimum ruby-version
# is 3.1 and core22 only includes 3.0
base: core24
version: '6.15.3'
summary: A harmonica tool for the command line, using microphone and speaker
description: |
  Harpwise supports your harmonica practice with scales, chords and licks.
  It offers various tools, an explorable quiz and may guide your jamming.
  It can be used with diatonic (richter) or chromatic harmonicas in
  different keys.
license: 'MIT'
grade: stable
confinement: strict

apps:
  harpwise:
    environment:
      # core24 includes ruby 3.2
      # RUBYLIB is prepended to LOAD_PATH
      RUBYLIB: $SNAP/usr/lib/ruby/3.2.0:$SNAP/usr/lib/x86_64-linux-gnu/ruby/3.2.0
      GEM_PATH: $SNAP/usr/lib/ruby/3.2.0
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio      
      TERMINFO_DIRS: $SNAP/lib/terminfo:$SNAP/usr/share/terminfo
      # We set PULSE_SERVER here but may override it from within harpwise. This is because
      # ubuntu in WSL2 needs a different value.
      PULSE_SERVER: unix:/run/user/1000/pulse/native
    command: usr/bin/ruby $SNAP/harpwise
    plugs:
    - audio-playback
    - audio-record
    - home

parts:
  harpwise:
    plugin: dump
    source: harpwise
    stage-packages:
      - coreutils
      - ruby
      - libruby
      - rubygems
      - sox
      - libsox-fmt-mp3
      - libsox-fmt-pulse
      - libpulse0
      - pulseaudio-utils
      - alsa-utils
      - aubio-tools
      - figlet
      - toilet
      - ncurses-base
      - ncurses-term
      - pv
      - libsixel-bin

layout:             
  $SNAP/usr/bin/figlet:
    symlink: $SNAP/usr/bin/figlet-figlet
  /usr/lib/x86_64-linux-gnu/sox:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/sox
  /usr/share/figlet:
    bind: $SNAP/usr/share/figlet
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

lint:
  ignore:
    - library
    
