---
typical_hole: "+1"
named_sets:
    blow-low:
    - "+1"
    - "+2"
    - "+3"
    - "+4"
    - "+5"
    - "+6"
    - "+7"
    - "+8"
    draw-low:
    - "-1"
    - "-2"
    - "-3"
    - "-4"
    - "-5"
    - "-6"
    - "-7"
    - "-8"
    blow-full:
    - "+1"
    - "+2"
    - "+3"
    - "+4"
    - "+5"
    - "+6"
    - "+7"
    - "+8"
    - "+9"
    - "+10"
    - "+11"
    - "+12"
    draw-full:
    - "-1"
    - "-2"
    - "-3"
    - "-4"
    - "-5"
    - "-6"
    - "-7"
    - "-8"
    - "-9"
    - "-10"
    - "-11"
    - "-12"
